# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/hotdogb/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),hotdogb)

$(call add-radio-file-sha1-checked,radio/LOGO.img,a5c74a189ab7550cc881bb4bdc47c80f761c8a41)
$(call add-radio-file-sha1-checked,radio/abl.img,baf8389e8c71ae4bc8ea3b1653cf24820584d5f7)
$(call add-radio-file-sha1-checked,radio/aop.img,94053385ac5ab5f7d1decce8f3bfec7d6a1f1237)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,51ea87b23e67ae47d8c45749d3e1c752a289cd41)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,958c44582bb264d0dcc5bab2fb10716535498e78)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,686e2debfb69f67c1ff6864417c3c14175b77171)
$(call add-radio-file-sha1-checked,radio/devcfg.img,271d5102182817a708e875f5f802499492f1ce1b)
$(call add-radio-file-sha1-checked,radio/dsp.img,4d47e695086ce7e79b7004055e364edc2ad8e46f)
$(call add-radio-file-sha1-checked,radio/hyp.img,8260daa6a8d868c5f5aadc211cca5f53f68f2c00)
$(call add-radio-file-sha1-checked,radio/imagefv.img,aa93c7f816b77c8c173a9ddfb6ad682edcfbb6f1)
$(call add-radio-file-sha1-checked,radio/keymaster.img,e8aed11742e3b106e08ddb260879edd550304832)
$(call add-radio-file-sha1-checked,radio/modem.img,e78fccf2f17e4ccb086846fa51064842f9692a85)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,7d74ce3f3657fc1e2c4eadebf5578a33637ef631)
$(call add-radio-file-sha1-checked,radio/qupfw.img,af543aa145b46d803e017e83d8901ad00723c6fc)
$(call add-radio-file-sha1-checked,radio/storsec.img,519069bdc87bb2ae1bd29bc4d4dfa5edc981d7cc)
$(call add-radio-file-sha1-checked,radio/tz.img,d3d9757173831cf8e423ca44ea0b7ed9a9d3ebd4)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,b0b874b3ac7ce280c6add63586bca9c654f798ff)
$(call add-radio-file-sha1-checked,radio/xbl.img,934de335078e5b67930166b0c8125f6020d4ff1e)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,80d0f25ca757bda55e90cc86f9cc7f4830d87aae)
endif
